version: "3"
services:
  spider:
    image: atwoodsun/grocy-companion:1.1.1
    restart: always
    ports:
      - "9288:9288"
    volumes:
      - ./config.ini:/usr/src/app/config.ini
    networks:
      - grocy_campanion

networks:
  grocy_campanion:
